sudo: required
services: 
 - docker


before_install:
  - docker build -t fezerik/react-docker -f Dockerfile.dev .

script:
  - docker run fezerik/react-docker npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "react-docker"
  env: "ReactDocker-env"
  bucket_name: elasticbeanstalk-ap-southeast-2-048536714619
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"